export const Approutes = {
  home: "/",
  welcome: "/welcome",
  aboutUs: "/about-us",
  contactUs: "/contact-us",
  auth: "/auth",
  forgotPassword: "/forgot-password",
  verifyMail: "/auth/verifyaccount",

  // categories routes
  automobile: {
    initial: "/automobile",
    cars: "/automobile/cars",
    motorbikes: "/automobile/motorbikes-scooters",
    vans: "/automobile/vans",
    trucks: "/automobile/trucks-lorries",
    accessories: "/automobile/accessories-parts",
    scooters: "/automobile/scooters",
    tractors: "/automobile/tractors-plants",
    automobileEquipments: "/automobile/automobile-equipments",
    bestDeals: "/automobile/best-deals",
    wanted: "/automobile/wanted",
    request: "/automobile/request",
    others: "/automobile/others",
  },
  property: {
    initial: "/property",
    forSale: "/property/for-sale",
    toLet: "/property/to-let",
    toShare: "/property/to-share",
    forLease: "/property/for-lease",
    landForSale: "/property/land-for-sale",
    forMosque: "/property/for-mosque",
    forChurch: "/property/for-church",
    shortLet: "/property/short-let",
    commercial: "/property/commercial",
  },
  services: {
    initial: "/services",
    business: "/services/business-office",
    childCare: "/services/child-care",
    clothing: "/services/clothing",
    food: "/services/food-drink",
    suppliers: "/services/suppliers-retailers",
    legal: "/services/legal-finance",
    animals: "/services/animals-pets",
    property: "/services/property-maintenance",
    farming: "/services/farming",
    clothes: "/services/clothes-foothwears",
    tradesmen: "/services/tradesmen-construction",
    transport: "/services/transport",
    weddings: "/services/weddings",
    tutorials: "/services/tutorials-classes",
    entertainment: "/services/entertainment",
    travel: "/services/travel-tourism",
    others: "/services/others",
  },
  forSale: {
    tv: "/for-sale/tv-dvd-videos",
    phones: "/for-sale/phones-mobile-phones-telecoms",
    music: "/for-sale/music-films-books-games",
    clothes: "/for-sale/clothes-footwears-accessories",
    tools: "/for-sale/diy-tools-materials",
    computers: "/for-sale/computers-software",
    office: "/for-sale/office-furniture-equipment",
    cameras: "/for-sale/cameras-camcoders-studio-equipment",
    audio: "/for-sale/audio-stereo",
    printers: "/for-sale/printers-scanners",
    baby: "/for-sale/baby-kids-items",
    home: "/for-sale/home-appliances",
    audio: "/for-sale/audio-stereo",
    softwares: "/for-sale/softwares",
    christmas: "for-sale/christmas-decor",
  },
};

export const backendLink = "http://109.237.25.252:4000/";
